### PR TITLE
Sample Improved and two major bug fixes

### PR DESCRIPTION
**Pull request by Ashok-Varma**
Two Major Bug fixes :-
1) null pointer when user not initialised mapColorForTab.
2) null layoutParams issue

and improved sample for users

### CODE REVIEW

**Comment by Ashok-Varma** [comment]
bug fix when there is no parent for view in attach method and also when user might not have called mapColorForTab in that case the hashMap will be null and app crashes.
improved samples so users can check different ways to add bottom-bars easily

**Comment by roughike** [comment]
The colorMap is already initialized properly if null in the ```mapColorForTab()``` method, so it won't be null afterwards.

I'll look into the other stuff when I can though, thanks.

**Comment by Ashok-Varma** [comment]
@roughike in your mainActivity try removing all five mapColorForTab, and test. It will crash

**Comment by roughike** [comment]
Holy shitballs, you're right! Will merge ASAP.

**Pull request merged**
