### PR TITLE
Data binding fixes

### PR DESCRIPTION
**Pull request by tushar-acharya**

### CODE REVIEW

**Comment by yombunker** [comment]
@tushar-acharya before i look into your change, can you not commit the changes to the .idea folder. cause it makes harder to look at the real change.

**Comment by yombunker** [comment]
@tushar-acharya again, can you please REMOVE the changes that you pushed to the .idea folder and just send the real changes if not i can't approve or even review this PR

**Comment by tushar-acharya** [comment]
@yombunker I've removed the changes in .idea folder completely from the repo as it changes based on the IntelliJ session. I'm not sure if there's any reason in keeping it in the github repo. If you want me to keep the .idea folder contents as is, I can revert he change

**Comment by yombunker** [comment]
@tushar-acharya  i know what you are doing, but, has nothing to do with the "fix for data binding", you can send that, but as a separate PR, we might want to keep some of the files in the .idea folder so that everyone uses the same code style and same copyright or something, but, we can talk about it as a separate issue, thanks.

**Comment by tushar-acharya** [comment]
Created a new PR #712 Closing this

**Pull request closed without merging**
