### PR TITLE
Bug using custom colors

### PR DESCRIPTION
**Pull request by Studentessa**
Fixed error in tablets produced when using custom colors of @mikemila. If custom color is used in tablets it has the same color behavior as phones does.

### CODE REVIEW

**Comment by yombunker** [comment]
@Studentessa is this a thing in the latest version?

**Comment by Studentessa** [comment]
Hello, I did this time ago, when it was libraryVersion = '1.4.0'.
I haven't work with the new one, but I will check if this is still reproducing in the latest version.

**Comment by yombunker** [comment]
@Studentessa thanks, let us know and we can see what we can do about it.

**Comment by Studentessa** [comment]
@yombunker I've checked if it's still happening in the last version bu is not! :)

**Comment by yombunker** [comment]
@Studentessa ok, thanks, im closing this bug :)

**Pull request closed without merging**
