### PR TITLE
Fix .gitignore and idea removed

### PR DESCRIPTION
**Pull request by ppamorim**
Hi, can you merge these fixes?

### CODE REVIEW

**Comment by ppamorim** [comment]
@roughike Please merge #14 first.

**Comment by ppamorim** [comment]
@roughike can you merge?

**Comment by roughike** [comment]
I'll review and merge when I can.

I remember having some problems when I tried to import some project from GitHub that didn't have the *.iml files. The project wouldn't just open for me if I recall correctly.

If all is fine after I check this, I'll merge. Thanks.

**Comment by livotov** [comment]
No, with the gradle-based build you may safely remove AS project files from the repo. AS will reconstruct the project files by parsing gradle files.

**Comment by ppamorim** [comment]
@roughike You need to re-import your project to create your .idea forder. Otherwise the project cannot compile.

**Comment by ppamorim** [comment]
@roughike ?

**Comment by roughike** [comment]
Been a busy week, but now it's done.

Thanks for contributing!

**Pull request merged**
