### PR TITLE
Fixed views not being removed from the item container.

### PR DESCRIPTION
**Pull request by NegreaVlad**
In order to remove all children you have to remove child at index 0 or
have indexes go in a decreasing order.

After removing child 0, all children go an index down.
If you have 3 views to remove, you remove position 0, then position 2,
when you get to position 3, this child will not be deleted, because
there no longer is a child at index 3. The only child is at position 0.

I was having trouble changing my BottomBarTabs. A view was not removed because of this.

### CODE REVIEW

**Comment by ygnessin** [comment]
Maybe I'm missing something, but why can't [removeAllViews()](https://developer.android.com/reference/android/view/ViewGroup.html#removeAllViews()) be used instead of iterating over each child one by one?

**Comment by NegreaVlad** [comment]
@ygnessin You are right [removeAllViews()](https://developer.android.com/reference/android/view/ViewGroup.html#removeAllViews()) is probably the better approach. I did not want to change very much code, because I'm not very familiar with the project, that's why I did not use that.

**Comment by roughike** [comment]
Although this thing is a spaghetti code hell, ```removeAllViews()``` would be right for this and it doesn't affect negatively elsewhere. If you want credit for this, just update this PR with ```removeAllViews()``` instead of the loop. Also a nice catch.

**Comment by NegreaVlad** [comment]
@roughike 
I have updated the pull request. Nice work on the library. Keep up the good work!

**Pull request merged**
