### PR TITLE
Fixed issues #4 and #9. See changelog for the rest of the improvements.

### PR DESCRIPTION
**Pull request by runemart**

### CODE REVIEW

**Comment by ppamorim** [comment]
`.idea` is not needed for the project, it's auto generated. Solved at #12

**Comment by runemart** [comment]
I agree, ppamorim. (I just ignored it instead of removing it).

**Comment by ppamorim** [comment]
@roughike please merge this first

**Comment by roughike** [comment]
The problem with inflating from XML is that it won't work on tablets the same way. On larger screen the BottomBar should be at the left, but then it will have problems with overlapping content. Tablets should be automatically handled by the library (as they now are), not the user.

When somebody figures a way to add the BottomBar by XML that both works with phones and tablets, I'll be happy to merge. I've tried it, but haven't found the solution yet.

Also, please don't remove existing functionality / methods, as the library has already a quite large userbase and we don't want to break their code.

There were some good bits and improvements I merged, thanks for your contribution on those.

**Comment by alorma** [comment]
Maybe a good way to handle tablets, is to create a custom ViewGroup.

We will set that VG, and inside it, our content, and the lib will display bottombar, or left bar :D

**Pull request merged**
