### PR TITLE
[Bug Fix] Tabs of incorrect size

### PR DESCRIPTION
**Pull request by yombunker**
- Setting the modified LayoutParams so that the views are changed

### CODE REVIEW

**Comment by roughike** [comment]
Is there a bug report related to this, or is this something you just found out?

**Comment by yombunker** [comment]
@roughike you reported it jajajaj #718

**Comment by roughike** [comment]
Ahh I guess I should go to sleep now.

**Comment by yombunker** [comment]
@roughike yeap, go to sleep, there's no rush on this release.

**Pull request merged**
