### PR TITLE
enable Badge set String

### PR DESCRIPTION
**Pull request by futabooo**
I want to set type string badge.
so I add setBadgeSymbol()

device-2017-03-29-162744

### CODE REVIEW

**Comment by roughike** [comment]
I believe @yombunker is currently working on something similar, that will allow major customization options for badges, including something like this too.

**Comment by yombunker** [comment]
@roughike yeah you can see the current state of the change in the branch named custom badges, i need to do some cleaning and fix some small issues and then it will be ready

**Comment by futabooo** [comment]
@roughike @yombunker It is cool!! I am looking forward :-)
and I close this pull request.

**Comment by yombunker** [comment]
@futabooo thanks for the effort of putting up a PR :)

**Comment by futabooo** [comment]
@yombunker hi! I am still looking forward :)

**Pull request closed without merging**
