### PR TITLE
fix for calculating width of tabs

### PR DESCRIPTION
**Pull request by xklakoux**
fixed faulty pixel to DP conversion, that caused first and last tab to go outside bounds of bar
fixed active tab width for active element in shifting mode

### CODE REVIEW

**Comment by yombunker** [comment]
@roughike what do you think about this change, i think is something good to have.

**Comment by roughike** [comment]
@xklakoux @yombunker I'm not 100% sure what this fixes. I wasn't able to reproduce any tabs going out of screen with even as much as 12 shifting tabs.

If you'd be able to give me steps to redproduce this problem, it would help.

**Comment by yombunker** [comment]
@roughike don't know about the "-1" that he added, but, the way to calculate the DP i do like to use "metric.density" instead of calculating it. But it will be good if @xklakoux could describe the problem that the "-1" solves

**Comment by roughike** [comment]
Okay, so at least that metric.density part is good to go.

The "-1" needs to be confirmed, since that tab calculation logic is a major backbone for the visual appearance of all tabs in mobile mode, both fixed and shifting.

**Comment by xklakoux** [comment]
I'm happy to provide sample code to illustrate the problem whenever I have some free time, however the -1 part you can simply test by doing some calculations. 

Each inactive tab gets 90% of calculated width. Active tab takes those remaining 10% of them but also for itself which is incorrect because we do not substract its width to 90% before. Then ie. for 4 tabs it gets 140% of average width instead of 130% and it adds up for more space that we have in view for whole bar. It's subtle bug but it's present. I hope I expressed myself clearly.

**Comment by roughike** [comment]
@xklakoux I was able to verify the tabs go a tiny bit out of the screen edges by using the Layout Inspector. You're absolutely right! While the difference is indistinguishable for the naked eye, it's still there. 

So this PR, with all of its entirety, definitely should be merged. 

@yombunker I can merge this, but I'm not sure what happens with your existing upcoming changes.

**Comment by yombunker** [comment]
@roughike i was going to do the exact same thing, but, i saw this PR, you can merge it with no problem

**Pull request merged**
