### PR TITLE
Show & Hide methods when on shy mode.

### PR DESCRIPTION
**Pull request by roughike**
This needs some input:

- Is the method naming on point? Could it be misinterpreted somehow?
- Do we want to support hide / show methods when NOT on shy mode? The layouts can be quite complex and I personally think hiding the regular (=not shy) BottomBars should probably be the user's job, as this is a regular view after all.

### CODE REVIEW

**Comment by yombunker** [comment]
@roughike names do sound kind of weird and confusing, but, this is also a functionality that is only available under certain circumstances

**Comment by yombunker** [comment]
@roughike the only way i can think of this not been weird, is if the shy behavior is not an added, but, another view that extends from BottomBar and that has those methods, so that you can only use the shy behavior on that view, and thus the normal bar will not have the show/hide methods, but, seems to be quite a breaking change to do that (maybe a good thing maybe not)

**Comment by roughike** [comment]
I made some changes. Now the usage looks like this:

```java
bottomBar.getShySettings().showBar();
bottomBar.getShySettings().hideBar();
```

Let me know if this could be improved upon further.

**Comment by roughike** [comment]
The reason for not making a ```ShyBottomBar``` that extends from ```BottomBar``` is that if somebody would like to use a shy BottomBar on mobile, but a tablet one on tablets, that would require some different logic and possibly casting.

Now that I'm thinking of it, would it be better to have the ```getShySettings()``` return null instead of throwing an exception? That way, on tablets there's no need for try-catch if you're showing / hiding shy BottomBars on mobile mode. Or maybe make all calls ```getShySettings()``` no-ops and display a log warning message when the bar isn't shy?

**Comment by yombunker** [comment]
@roughike i would rather have the no-op than having to check for nullity

**Comment by roughike** [comment]
No-op with log warnings is added in the latest commit.

**Pull request merged**
