### PR TITLE
Added selectableitembackground to tabs, a couple fixes and updated gradle plugins

### PR DESCRIPTION
**Pull request by MarcRubio**
I think title and commit comments describe the small changes I made. I simply added the selectableitembackground so each tab give that nice subtle feedback of it being touched.

### CODE REVIEW

**Comment by roughike** [comment]
Hey @MarcRubio and thanks for your work!

It seems that something in your changes makes the vertical centering of the tabs break, and they end up a little higher than center. That minor offset is hard to spot in the ThreeTabsActivity (although still there), but you can really see it in **CustomColorAndFontActivity**.

If you're able to fix that, we're good to go!

**Comment by MarcRubio** [comment]
Ok, so the change kinda comes from commit 	[https://github.com/roughike/BottomBar/pull/420/commits/581f0657d456de766190fab1b2aa36b71b3462e7](url) where we get the height directly from the xml.

This small issue is dependent on the height set in the xml by the developer.
The material design guidelines says the height should be 56dp and I have found that anything between and including 56dp and 60dp seems to work well.

In the examples we are using 60dp for ThreeTabsActivity, 64dp CustomColorAndFontActivity and 56dp for ColorChanginTabsActivity so we are not being very consistent, also, the Custom Font seems quite large.

Overall, I think the best and easiest solution is to revert it back to your original solution where you default the height to 56dp in the resizeTabsToCorrectSizes() method . The selectableItemDrawable works well as long as developers **don't** define a height > 60dp for their bottomNavBar in the xml which is why I made tried this tweak in the first place.

Maybe in your Readme you can state that the recommended height is in the range of 56dp - 60dp going by the material design guidelines which says 56dp.

I will make a small tweak to the customfontactivity example and you can judge from that.

**Comment by roughike** [comment]
**The issue still persists on ThreeTabsActivity** as well. If you look closely, the tabs are not centered vertically.

I agree with you on the bar height being in the 56dp - 60dp range, but it should still center the tabs vertically with larger heights IMO.

I'll look into this and fix it when I have time.

Still appreciate the PR!

**Comment by MarcRubio** [comment]
Woaaaah hang on, my git revert initially did as intended but once I pushed it seems like it merged the code I had originally deleted which is why there no difference :fearful: . 

My next and hopefully final commit should fix it :+1:

**Comment by berrym72** [comment]
@roughike Will this fix be in v2.0.3? And when do you think that will be released? I would really like to get the ripple effect back. Thanks.

**Comment by Nominalista** [comment]
@roughike I'm also waiting for ripple effect.

**Comment by yombunker** [comment]
@MarcRubio can you modify your PR to ONLY include the files that need to be modified, ignore the .iml and things like that when you push, just push the real changes. And are the changes to the style really required? cause it seems that the only real code related to your title, is the 3 lines that get the background and set it. i'm i right?

**Comment by roughike** [comment]
I'll make sure that the .gitignore is correct and those unneeded Intellij IDEA files get untracked from the version control when I can, so this doesn't happen again.

**Comment by yombunker** [comment]
@roughike that's good, but, still his PR should only include the real changes :)

**Comment by MarcRubio** [comment]
It has been a while since I did this and the project seems to have moved ahead quite a bit therefore I will close this pull request and simply make a new one adding the few lines of code to the lib which add the ripple. I have quickly tested this and it seems to be fine. I'll ensure I don't change or add any other unnecessary files.

**Comment by yombunker** [comment]
@MarcRubio sounds good.

**Pull request closed without merging**
