### PR TITLE
add feature: set dark theme background color

### PR DESCRIPTION
**Pull request by westlinkin**
You can use dark theme with different color other than black `#212121`

### CODE REVIEW

**Comment by cmendes0101** [comment]
+1

**Comment by drozdzynski** [comment]
+1

**Comment by narfman0** [comment]
Missing a couple 'k's but :+1:

**Comment by yombunker** [comment]
@westlinkin can you explain what this is fixing that you can't get with the current code.

**Comment by roughike** [comment]
This was submitted also when the project was v1 phase, when there was no way to specify custom dark theme.

**Comment by yombunker** [comment]
@roughike closing it then :)

**Pull request closed without merging**
