### PR TITLE
Snackbars don't go above the bottom bar with attachShy() 

### LINKED ISSUE #89: Snackbars don't go above the bottom bar with attachShy()
I give my snackbar the root CoordinatorLayout and it was showing above the bottom bar when using just attach(this, ...) (as described in the issue  ["Snackbars should go above the bottom bar. #36" ](https://github.com/roughike/BottomBar/issues/36)) but when I now use attachShy() it overlaps the bottom bar.

### PR DESCRIPTION
**Pull request by NikolaDespotoski**
Fixes #89 on all supported API levels

### CODE REVIEW

**Comment by roughike** [comment]
I love you. 

This works perfectly without the transparent Navigation Bar. With transparent Navigation Bar, there's a problem with the height as shown below:

screenshot_20160331-110616

Since you seem to be the Jedi Master of Behaviors, do you wanna fix this and get some credit?

(And if you wan't, I'll be happy to add you as contributor for this project, as I could use a hand)

**Comment by NikolaDespotoski** [comment]
@roughike  Fixing it as we speak. I'll make another PR in a few

**Comment by NikolaDespotoski** [comment]
@roughike Is this on N?

**Comment by roughike** [comment]
This is in Android M (6.0.1), on my Nexus 5.

**Comment by NikolaDespotoski** [comment]
@roughike Can you also post how do you bind the bottom bar? What do you set for content view argument? Thanks.

**Comment by roughike** [comment]
I'm using the exact same setup as described in the Readme for attaching BottomBar to a CoordinatorLayout.

**MainActivity.java:**

```java
mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.myCoordinator), 
    findViewById(R.id.myScrollingContent), savedInstanceState);
```

**activity_main.xml:**

```xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/myCoordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/messageView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"/>

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>
```

**Comment by NikolaDespotoski** [comment]
@roughike Thanks, fixed it.  android:fitsSystemWindows="true" was the clue. Committing.

**Comment by NikolaDespotoski** [comment]
@roughike PR #117 fixes this case.

**Pull request merged**
