### PR TITLE
Added the ability to set a custom background color, custom tab icon colors, and icon alpha

### PR DESCRIPTION
**Pull request by mikemilla**
Changed these colors and also changed the bottom bar shadow to not be as intense. Also add the activity to the sample app to see this in action.

screenshot_20160617-150914

### CODE REVIEW

**Comment by felipeleusin** [comment]
Thanks, I was about to write a similar pull request. Imho this whole color thing should be the less magical possible. It should just inherit the app themes colors and allow for substitutions without worrying too much about what the users set.

**Comment by mikemilla** [comment]
Exactly. Material design guidelines are just guidelines, not specific rules we have to follow.

**Comment by wuchangfeng** [comment]
@mikemilla Thanks. Very cool. That is what i want.

**Comment by wuchangfeng** [comment]
@mikemilla   hi. I  used your code and what the effect like in my example just like the below. img  and code here.
What am I doing wrong ？
thx.



··· java
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_basic);
        // Customize the colors here
        mBottomBar = BottomBar.attach(this, savedInstanceState,
                Color.parseColor("#FFFFFF"), // Background Color
                ContextCompat.getColor(this, R.color.colorAccent), // Tab Item Color
                0.25f); // Tab Item Alpha

        mBottomBar.setItems(R.menu.bottombar_menu);

        mBottomBar.setOnMenuTabClickListener(new OnMenuTabClickListener() {
            @Override
            public void onMenuTabSelected(@IdRes int menuItemId) {
               // mMessageView.setText(TabMessage.get(menuItemId, false));
            }

            @Override
            public void onMenuTabReSelected(@IdRes int menuItemId) {
                Toast.makeText(getApplicationContext(), TabMessage.get(menuItemId, true), Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        // Necessary to restore the BottomBar's state, otherwise we would
        // lose the current tab on orientation change.
        mBottomBar.onSaveInstanceState(outState);
    }
···

··· xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.NoActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary" />

    </android.support.design.widget.AppBarLayout>

    <TextView
        android:id="@+id/tv"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:text="hello"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
android:layout_gravity="bottom|end"        
android:layout_margin="@dimen/fab_margin"
        android:src="@android:drawable/ic_dialog_email" />

</android.support.design.widget.CoordinatorLayout>
···

**Comment by Studentessa** [comment]
Hi @mikemilla when I started using this new ability (great ability any way, I was watting for this), apps crahs in terminal with api < 21. 
Do i have to open a new issue?

**Comment by DanielKou** [comment]
Hey, how do I use this? Which method do I call to set the custom icon colors?

**Comment by Studentessa** [comment]
@DanielKou you set colors using the constructor, like this:
` mBottomBar = BottomBar.attach(this, savedInstanceState,
                Color.parseColor("#FFFFFF"), // Background Color
                Color.parseColor("#0DA5F2"), // Tab Item Color
                0.25f);`

**Comment by mikemilla** [comment]
@Studentessa I can't remember if I tested it on a preAPI21 device or not! Feel free to make adjustments to this code if you'd like or I will investigate when I get a chance.

Also, thank you for addressing Daniel's issue :)

**Comment by Studentessa** [comment]
@mikemilla the problem is no on preAPI21, it's using tablets with mIsTabletMode activate (I was testing on a preAPI21 tablet deviced). 
I will try to fixed the problem, I have found why is the problem (mInActiveColor is null when we set customs colors)!

**Comment by mikemilla** [comment]
@Studentessa ok, thank you for finding it :)

**Pull request merged**
