### PR TITLE
Fix bottom bar height to be 56dp

### LINKED ISSUE #168: BottomBar height not 56dp
The height of the bottom bar should be **56dp** according to the [Material Design Specs](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-specs).
It is too high at the moment.

### PR DESCRIPTION
**Pull request by jush**
* New items in the bottom bar container are now 56dp tall
* Title doesn't not move when its state changes between active/inactive
* Title has now 10dp padding bottom from its baseline
* Title is now forced to be one line max

This pull request should fix #168 and override #185

### CODE REVIEW

**Comment by philipgiuliani** [comment]
Awesome! 👍  Just looked for this ! :)

**Comment by jush** [comment]
If somebody is interested you can use this fix already in your project by adding the jitpack repo to your project:
```
allprojects {
 repositories {
    jcenter()
    maven { url "https://jitpack.io" }
 }
}
```
and then as dependency:
```
compile 'com.github.jush:BottomBar:1.3.3-fixed-height'
```

**Comment by philipgiuliani** [comment]
Thank you very much @jush to publish it so i can use it already! I tried it on a lot of different devices and it looks good everywhere. Will use this branch until it's merged!

**Comment by jd-alexander** [comment]
I tried to use this but the bottombar became collapsed (about half it's size; icons overlapping titles). Wondering if it's because I have to set the height with the attribute in the dimens.xml file..I did that but stil didnt work.

**Comment by jush** [comment]
@jd-alexander the size of the icons must be 24dp by 24dp.

**Comment by jd-alexander** [comment]
That's how it looked after I updated to the latest version, same effect as when I was using your branch and my icons are 24dp so I am not sure why this is happening.
new_bottom_bar

**Comment by jush** [comment]
@jd-alexander could you enable "show layout bounds" from the developer options and take the screenshot again? I'm guessing that's an xxhdpi device, isn't it?

I didn't test extensively when having more than 3 icons and force show the title since it's not recommend in the material spec.

**Comment by roughike** [comment]
See the changelog for the 1.3.4:

* Now the BottomBar is 56dp tall, as it should be! Make sure your icons are 24dp and **untrimmed**, meaning that the whole png size musn't be more than 24dp.

**Pull request merged**
